language: go
sudo: false
go: 1.7
install:
  - go build -v .
  - echo ls -al $TRAVIS_BUILD_DIR
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: OCFtl1BG3wtuvd0jKvN9Ggsx7QKhE8/TXB/lHCsYZrsc9JZ+WuDhqgw6Lf54A4a1vz3o26W0i4T/D8PTe3wInE5Zzgd82i7rml+vaJgoQkxfTrDDCySWopoTGN1Gq0hgIeESP1cwZQBoIa03frbf87qSFx6DTZSFptOcE3fPbhpAWCdz43vGOmM5S93eH2vC31dYBBSlAYhahnYYzUxZ8TcWlgXAniO5ijp55m4iKZK9ImtbLpJ8kXHobGjHUtMjWMko/muYFtG48tYnAyo2TcPRN4qCSQNZrKmNd4AKmQwn2OjiyrLI5HJmeSvOTjCKrTtN3vgd9ArYI43b6bAvCScbI4RVRRoxbVFTp5xi/MrVNuAK8vK+YE9uXfTa3JM9AOUKJo062Vm3wJ1tzOxPbRrQs5BQlYyPpawjP93UJweHlTrPm6A7t4FswhuamJAefFkXpZRSRIvF/xLgVxjZyvdZZCxfQm1SD3JdR6G4ftlPIX17tCVUkvKA1cggUxDZhKRRQJViIHs28DCNjbOIlKbU0sL7mnRow2GwDcoaMEGn0P3yuThNiQSghyGobbsZ0WIr0a6P+ZzFKHRbBR8fZy3kMX0+xNsSLXH2u5sWFrvO6J4H0AWO3OLoZkQXGbUv4UOtkRqKPBB825gVfDYco5am6oHOIHJEzTgiQLUKNnA=
  on:
    repo: VEVO/kubernetes-updater
    branch: gocd
  file:
    - roller
  on:
    tags: true
    repo: VEVO/kubernetes-updater
